In [16]:
import numpy as np

In [25]:
A = np.array([[1, 4, 2, 3, 1], [1/4, 1, 1/2, 1/2, 1/4], [1/2, 2, 1, 1/2, 1/2], [1/3, 2, 2, 1, 1/3], [1, 4, 2, 3, 1]])
A.shape[0]

5

In [20]:
a=np.array([1,2,3,4])
a.shape[0]

4

In [5]:
b=[2,3,4,5]
a+b
[x+y for (x,y) in zip(a,b)]

[3, 5, 7, 9]

In [7]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [8]:
np.ones(6,dtype='bool')

array([ True,  True,  True,  True,  True,  True])

In [14]:
a.fill(3)
a

array([3, 3, 3, 3])

In [24]:
a=a.astype('str')
a.fill('hha')
print (a)

['hha' 'hha' 'hha' 'hha']


In [26]:
a=np.linspace(1,10,21)
print (a)

[ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]


In [28]:
a=np.random.randint(1,20,40)
print(a)

[12  1 14  7 12  1 14 17 18 12 19  8 16 13 11 17 12 17 13  2  6  1  9  6
 12 12  4  6 17  4 11 10  5  2  4  8  3  5 10 17]


In [14]:
a.size

6

In [32]:
a=np.array([1,2,3,4])
a[0]=10
a

array([10,  2,  3,  4])

In [36]:
a=np.array([[1,2,43,4],[4,7,32,5]])
a

array([[ 1,  2, 43,  4],
       [ 4,  7, 32,  5]])

In [39]:
print (a[0,1:3])

[ 2 43]


In [40]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
p=[1,2,-3]
y=a[p]
print(y)

[10 20 70]


In [49]:
a=np.array([0,12,5,20])
print (a>10)
np.where(a>10)

[False  True False  True]


(array([1, 3], dtype=int64),)

In [51]:
a[a>10]

array([12, 20])

In [52]:
a[np.where(a>10)]

array([12, 20])

In [54]:
a=np.array([1.5,-3],dtype=float)
a

array([ 1.5, -3. ])

In [4]:
a=np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [4]:
a=np.array([1,6,3])
np.sort(a)

array([1, 3, 6])

In [5]:
order=np.argsort(a)
order

array([0, 2, 1], dtype=int64)

In [6]:
np.max(a)

6

In [8]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a.shape=2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
b=np.array([[1,2],[1,2]])
type(b)

numpy.ndarray

In [7]:
c=b.T
b@c

array([[5, 5],
       [5, 5]])

In [15]:
import numpy as np
n = int(input())
line = [[0]*n]*n
for i in range(n):
    line[i] = input().split(" ")
a = line
a@a

 1
 2


TypeError: unsupported operand type(s) for @: 'list' and 'list'