In [41]:
import math
import numpy as np
import sympy as sp

a = [[147227.00, 5.339, 171, 0.76, 1.20], [209366.00, 6.951, 172, 0.93, 6.94],
     [31084.00, 7.064, 168, 0.93, 4.74], [50577.00, 5.94, 167, 0.92, 4.00],
     [26229.80, 3.819, 159, 0.65, 0.21], [14835.00, 5.477, 170, 0.82, 1.16],
     [818.00, 4.275, 0, 0.49, 0.08]]
b = sp.Matrix(a)
e = sp.Matrix(a)
c = b.T @ b
d = np.empty(10)
for i in range(5):
    d[i] = math.sqrt(c[i, i])
    print(d[i])
for i in range(5):
    e[:, i] = b[:, i] / d[i]
print(e)


264467.21578872495
14.995430403959736
411.2408053683389
2.118678833613061
9.458715557621977
Matrix([[0.556692819414015, 0.356041797812630, 0.415814767814296, 0.358714113693176, 0.126867119820833], [0.791651998814312, 0.463541213072784, 0.418246433123152, 0.438952797019281, 0.733714842963815], [0.117534416911743, 0.471076842058142, 0.408519771887730, 0.438952797019281, 0.501125123292288], [0.191241095230512, 0.396120674097588, 0.406088106578874, 0.434232874470686, 0.422890399402775], [0.0991797789445260, 0.254677584912237, 0.386634784108030, 0.306794965658637, 0.0222017459686457], [0.0560939092422376, 0.365244601352271, 0.413383102505441, 0.387033648984742, 0.122638215826805], [0.00309301097136167, 0.285086848782355, 0, 0.231276204881126, 0.00845780798805550]])


In [2]:
f=np.array([[0.556692819414015, 0.356041797812630, 0.415814767814296, 0.358714113693176, 0.126867119820833], 
            [0.791651998814312, 0.463541213072784, 0.418246433123152, 0.438952797019281, 0.733714842963815], 
            [0.117534416911743, 0.471076842058142, 0.408519771887730, 0.438952797019281, 0.501125123292288], 
            [0.191241095230512, 0.396120674097588, 0.406088106578874, 0.434232874470686, 0.422890399402775], 
            [0.0991797789445260, 0.254677584912237, 0.386634784108030, 0.306794965658637, 0.0222017459686457], 
            [0.0560939092422376, 0.365244601352271, 0.413383102505441, 0.387033648984742, 0.122638215826805], 
            [0.00309301097136167, 0.285086848782355, 0, 0.231276204881126, 0.00845780798805550]])
f

array([[0.55669282, 0.3560418 , 0.41581477, 0.35871411, 0.12686712],
       [0.791652  , 0.46354121, 0.41824643, 0.4389528 , 0.73371484],
       [0.11753442, 0.47107684, 0.40851977, 0.4389528 , 0.50112512],
       [0.1912411 , 0.39612067, 0.40608811, 0.43423287, 0.4228904 ],
       [0.09917978, 0.25467758, 0.38663478, 0.30679497, 0.02220175],
       [0.05609391, 0.3652446 , 0.4133831 , 0.38703365, 0.12263822],
       [0.00309301, 0.28508685, 0.        , 0.2312762 , 0.00845781]])

In [7]:
max=np.max(f,axis=0)
max

array([0.791652  , 0.47107684, 0.41824643, 0.4389528 , 0.73371484])

In [8]:
min=np.min(f,axis=0)
min

array([0.00309301, 0.25467758, 0.        , 0.2312762 , 0.00845781])

In [23]:
for i in range(7):
    print (f[i,4])

0.126867119820833
0.733714842963815
0.501125123292288
0.422890399402775
0.0222017459686457
0.122638215826805
0.0084578079880555


In [34]:
maxdistance = np.empty(7,dtype=float)
mindistance = np.empty(7,dtype=float)

In [38]:
for i in range(7):
    x = 0
    y = 0
    for j in range(5):
        x = x+math.pow(f[i,j] - max[j],2)
    maxdistance[i] = math.sqrt(x)
    for k in range(5):
        y = y+math.pow(f[i,k] - min[k],2)
    mindistance[i] = math.sqrt(y)
print (maxdistance[0])

0.6656930191694445


In [40]:
point = np.empty(7,dtype=float)
for i in range(7):
    point[i]=mindistance[i]/(maxdistance[i]+mindistance[i])
    print(point[i])

0.519958740134133
0.993692778709041
0.5009883181743418
0.49173061180193556
0.28353670136553194
0.3290140511621533
0.025052409512221693


In [42]:
A=np.array([1,1],[1,1])
pingfanghe = np.empty(A.shape[0], dtype=float)
# OMEGA = np.empty(A.shape[0], dtype=float)
x = 1
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        x = x * A[i, j]
    pingfanghe[i] = math.pow(x, 1/A.shape[0])
OMEGA = pingfanghe/np.sum(pingfanghe)
print(OMEGA)

TypeError: Field elements must be 2- or 3-tuples, got '1'