In [1]:
import numpy as np
import sympy as sp
import xlrd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
A=[[1,4,2,3,1],[1/4,1,1/2,1/2,1/4],[1/2,2,1,1/2,1/2],[1/3,2,2,1,1/3],[1,4,2,3,1]]
type(A)

list

In [12]:
B=A
B

[[1, 4, 2, 3, 1],
 [0.25, 1, 0.5, 0.5, 0.25],
 [0.5, 2, 1, 0.5, 0.5],
 [0.3333333333333333, 2, 2, 1, 0.3333333333333333],
 [1, 4, 2, 3, 1]]

In [33]:
type(B)

list

In [ ]:
A=sp.Matrix(A)
A

Matrix([
[                1, 4,   2,   3,                 1],
[             0.25, 1, 0.5, 0.5,              0.25],
[              0.5, 2,   1, 0.5,               0.5],
[0.333333333333333, 2,   2,   1, 0.333333333333333],
[                1, 4,   2,   3,                 1]])

In [8]:
A.rref()

(Matrix([
 [1, 0, -6.0, 0, 1.0],
 [0, 1,  2.0, 0,   0],
 [0, 0,    0, 1,   0],
 [0, 0,    0, 0,   0],
 [0, 0,    0, 0,   0]]),
 (0, 1, 3))

In [13]:
np.linalg.eig(B)

(array([ 5.13284690e+00+0.j       , -6.64234498e-02+0.8230861j,
        -6.64234498e-02-0.8230861j,  1.52339079e-16+0.j       ,
        -1.55256336e-16+0.j       ]),
 array([[ 6.40377785e-01+0.00000000e+00j,  5.66607193e-01+0.00000000e+00j,
          5.66607193e-01-0.00000000e+00j,  2.81319888e-01+0.00000000e+00j,
         -5.51192374e-01+0.00000000e+00j],
        [ 1.45466717e-01+0.00000000e+00j,  1.11930447e-02-6.42473785e-02j,
          1.11930447e-02+6.42473785e-02j, -3.80495743e-01+0.00000000e+00j,
         -9.22616988e-02+0.00000000e+00j],
        [ 2.61677975e-01+0.00000000e+00j, -2.38531418e-01-2.56989514e-01j,
         -2.38531418e-01+2.56989514e-01j,  1.90247872e-01+0.00000000e+00j,
          4.61308494e-02+0.00000000e+00j],
        [ 3.00327580e-01+0.00000000e+00j, -2.46186578e-01+4.12445015e-01j,
         -2.46186578e-01-4.12445015e-01j, -1.21572375e-16+0.00000000e+00j,
         -1.92511366e-17+0.00000000e+00j],
        [ 6.40377785e-01+0.00000000e+00j,  5.66607193e-01-2.22

In [18]:
b=np.sum(B,axis=0)

In [16]:
np.sum(B,axis=1)

array([11.        ,  2.5       ,  4.5       ,  5.66666667, 11.        ])

In [22]:
c=B/b
c

array([[0.32432432, 0.30769231, 0.26666667, 0.375     , 0.32432432],
       [0.08108108, 0.07692308, 0.06666667, 0.0625    , 0.08108108],
       [0.16216216, 0.15384615, 0.13333333, 0.0625    , 0.16216216],
       [0.10810811, 0.15384615, 0.26666667, 0.125     , 0.10810811],
       [0.32432432, 0.30769231, 0.26666667, 0.375     , 0.32432432]])

In [23]:
d=np.sum(c,axis=1)
d

array([1.59800762, 0.36825191, 0.67400381, 0.76172904, 1.59800762])

In [24]:
d/5

array([0.31960152, 0.07365038, 0.13480076, 0.15234581, 0.31960152])

In [27]:
A=np.diag((1,2,3))
#求矩阵特征值以及特征向量
eig_value,eig_vector=np.linalg.eig(A)
#这里将特征值从小到大排列，但是sorted_indices表示的是所在下标的索引
sorted_indices=np.argsort(A)
#这样我们就能求得最小特征值所对应的特征向量
print(b[sorted_indices[0]])


[13.          7.5         3.08333333]


In [28]:
C=np.diag((1,2,3))
np.linalg.eig(C)

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [31]:
eig_value,eig_vector=np.linalg.eig(C)
sorted_indices=np.argsort(C)
sorted_indices[0]

array([1, 2, 0], dtype=int64)

In [73]:
import numpy as np
import sympy as sp
a = np.array([[147227.00, 5.339, 171, 0.76, 1.20], 
              [209366.00, 6.951, 172, 0.93, 6.94],
             [31084.00, 7.064, 168, 0.93, 4.74], 
              [50577.00, 5.94, 167, 0.92, 4.00],
             [26229.80, 3.819, 159, 0.65,0.21], 
              [14835.00, 5.477, 170, 0.82, 1.16],
             [818.00, 4.275, 0, 0.49, 0.08]])
b=sp.Matrix(a)
b

Matrix([
[147227.0, 5.339, 171.0, 0.76,  1.2],
[209366.0, 6.951, 172.0, 0.93, 6.94],
[ 31084.0, 7.064, 168.0, 0.93, 4.74],
[ 50577.0,  5.94, 167.0, 0.92,  4.0],
[ 26229.8, 3.819, 159.0, 0.65, 0.21],
[ 14835.0, 5.477, 170.0, 0.82, 1.16],
[   818.0, 4.275,     0, 0.49, 0.08]])

In [83]:
c=b.T@b
c

Matrix([
[69942908227.04, 2946272.6262, 81547728.2, 411656.75, 2002100.898],
[  2946272.6262,   224.862933,   5825.584,  31.62463,   119.38741],
[    81547728.2,     5825.584,   169119.0,    842.55,     3093.79],
[     411656.75,     31.62463,     842.55,    4.4888,     16.5813],
[   2002100.898,    119.38741,    3093.79,   16.5813,     89.4673]])

In [76]:
import math
d = np.empty(a.shape[1])
for i in range(a.shape[1]):
    d[i]=math.sqrt(c[i,i])
    print(d[i])

514.2637609133321
3.8723933689592713
20.27907308947672
1.4555682167500983
3.07550248863856


In [84]:
for i in range(a.shape[1]):
    c[:,i]=c[:,i]/d[i]
c

Matrix([
[3978058.38316764, 2810139.15906144,  3001473.1463525, 2827027.87582309, 2548209.06345128],
[ 167.57159255813, 214.473069404886, 214.418406542695, 217.180237109172, 151.952421842415],
[4638.09172391365, 5556.41103176393, 6224.65086695068, 5786.16125394456, 3937.67553188268],
[23.4133041767336, 30.1634038763242, 31.0111790393113, 30.8265629775163, 21.1041406484623],
[113.871076612701, 113.871076612701, 113.871076612701, 113.871076612701, 113.871076612701]])