In [21]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

In [2]:
a=np.array([0.14755893, 0.18763014, 0.15956194, 0.14089971, 0.13242327, 0.11927418, 0.11265184])
np.sum(a)

1.00000001

In [24]:
b=np.array([4358945768,2118592432,493505520,7896810,922238143,1511173360,372605])
c=np.array([0.14755893, 0.18763014, 0.15956194, 0.14089971, 0.13242327, 0.11927418, 0.11265184])

In [11]:
d=b+100000000*c
d

array([4.37370166e+09, 2.13735545e+09, 5.09461714e+08, 2.19867810e+07,
       9.35480470e+08, 1.52310078e+09, 1.16377890e+07])

In [12]:
e=b+1000000000*c
e

array([4.50650470e+09, 2.30622257e+09, 6.53067460e+08, 1.48796520e+08,
       1.05466141e+09, 1.63044754e+09, 1.13024445e+08])

In [25]:
f=b+10000000000*c
f

array([5.83453507e+09, 3.99489383e+09, 2.08912492e+09, 1.41689391e+09,
       2.24647084e+09, 2.70391516e+09, 1.12689100e+09])

In [13]:
100000000*c

array([14755893., 18763014., 15956194., 14089971., 13242327., 11927418.,
       11265184.])

In [14]:
1000000000*c

array([1.4755893e+08, 1.8763014e+08, 1.5956194e+08, 1.4089971e+08,
       1.3242327e+08, 1.1927418e+08, 1.1265184e+08])

In [15]:
10000000000*c

array([1.4755893e+09, 1.8763014e+09, 1.5956194e+09, 1.4089971e+09,
       1.3242327e+09, 1.1927418e+09, 1.1265184e+09])

In [18]:
c=np.array([1490345193,1895064414,1611575594,1423087071,935480470,1523100780,11637789])
d=np.array([14762504.03,21433226,2826441.791,5082465.811,2891582.351,1692930.151,92750.11782])
a1=c-d
a1

array([1.47558269e+09, 1.87363119e+09, 1.60874915e+09, 1.41800461e+09,
       9.32588888e+08, 1.52140785e+09, 1.15450389e+07])

In [26]:
a = np.arange(3)
a

array([0, 1, 2])

In [27]:
b=np.arange(3,8,0.5)
b

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])