In [2]:
import numpy as np
import matplotlib
matplotlib.matplotlib_fname()

'D:\\00Softwares\\ANACONDA\\lib\\site-packages\\matplotlib\\mpl-data\\matplotlibrc'

In [6]:
A = np.array([[1, 4, 2, 3, 1], [1/4, 1, 1/2, 1/2, 1/4], [1/2, 2, 1, 1/2, 1/2], [1/3, 2, 2, 1, 1/3], [1, 4, 2, 3, 1]])
A

array([[1.        , 4.        , 2.        , 3.        , 1.        ],
       [0.25      , 1.        , 0.5       , 0.5       , 0.25      ],
       [0.5       , 2.        , 1.        , 0.5       , 0.5       ],
       [0.33333333, 2.        , 2.        , 1.        , 0.33333333],
       [1.        , 4.        , 2.        , 3.        , 1.        ]])

In [23]:
lamda = np.linalg.eig(A)
lamda

(array([ 5.13284690e+00+0.j       , -6.64234498e-02+0.8230861j,
        -6.64234498e-02-0.8230861j,  1.52339079e-16+0.j       ,
        -1.55256336e-16+0.j       ]),
 array([[ 6.40377785e-01+0.00000000e+00j,  5.66607193e-01+0.00000000e+00j,
          5.66607193e-01-0.00000000e+00j,  2.81319888e-01+0.00000000e+00j,
         -5.51192374e-01+0.00000000e+00j],
        [ 1.45466717e-01+0.00000000e+00j,  1.11930447e-02-6.42473785e-02j,
          1.11930447e-02+6.42473785e-02j, -3.80495743e-01+0.00000000e+00j,
         -9.22616988e-02+0.00000000e+00j],
        [ 2.61677975e-01+0.00000000e+00j, -2.38531418e-01-2.56989514e-01j,
         -2.38531418e-01+2.56989514e-01j,  1.90247872e-01+0.00000000e+00j,
          4.61308494e-02+0.00000000e+00j],
        [ 3.00327580e-01+0.00000000e+00j, -2.46186578e-01+4.12445015e-01j,
         -2.46186578e-01-4.12445015e-01j, -1.21572375e-16+0.00000000e+00j,
         -1.92511366e-17+0.00000000e+00j],
        [ 6.40377785e-01+0.00000000e+00j,  5.66607193e-01-2.22

In [8]:
index = np.argmax(lamda[0])
index

0

In [21]:
lamda_max = np.real(lamda[0][index])
lamda_max

5.13284689963236

In [22]:
vector = lamda[1][:, index]
vector

array([0.64037779+0.j, 0.14546672+0.j, 0.26167798+0.j, 0.30032758+0.j,
       0.64037779+0.j])

In [24]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [25]:
y=x.transpose((1,0))
y

array([[0, 2],
       [1, 3]])

In [26]:
y[0][1]

2

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
 
df = pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\学习excel.xlsx')
df[:5]

MatchID     TeamID OriginPlayerID DestinationPlayerID MatchPeriod  \
0        1    Huskies     Huskies_G1                 NaN          1H   
1        1  Opponent1   Opponent1_D1                 NaN          1H   
2        1    Huskies     Huskies_F1                 NaN          1H   
3        1  Opponent1   Opponent1_D2                 NaN          1H   
4        1    Huskies     Huskies_D1          Huskies_F1          1H   

   EventTime  EventType EventSubType  EventOrigin_x  EventOrigin_y  \
0  31.174681  Free Kick    Goal kick            0.0            0.0   
1  33.730326       Duel     Air duel           34.0           11.0   
2  33.812965       Duel     Air duel           66.0           89.0   
3  42.611028  Free Kick     Throw in           22.0            0.0   
4  46.323501       Pass    Head pass           34.0           97.0   

   EventDestination_x  EventDestination_y  
0                66.0                89.0  
1                22.0                 0.0  
2                78.0               100.0  
3                66.0                 3.0  
4                59.0                95.0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59271 entries, 0 to 59270
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   MatchID              59271 non-null  int64  
 1   TeamID               59271 non-null  object 
 2   OriginPlayerID       59271 non-null  object 
 3   DestinationPlayerID  23644 non-null  object 
 4   MatchPeriod          59271 non-null  object 
 5   EventTime            59271 non-null  float64
 6   EventType            59271 non-null  object 
 7   EventSubType         59131 non-null  object 
 8   EventOrigin_x        59056 non-null  float64
 9   EventOrigin_y        59056 non-null  float64
 10  EventDestination_x   59047 non-null  float64
 11  EventDestination_y   59047 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 5.4+ MB


In [46]:
df1=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\Merge-01.xlsx')
df2=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\Merge-02.xlsx')

In [47]:
df1

OriginPlayerID  EventOrigin_x
0     Huskies_G1              0
1   Opponent1_D1             34
2     Huskies_F1             66
3   Opponent1_D2             22
4     Huskies_D1             34
5     Huskies_F1             59
6   Opponent1_D1             41
7   Opponent1_M1             36
8     Huskies_F1             55

In [48]:
df2

OriginPlayerID  EventOrigin_y
0   Opponent1_F1             44
1     Huskies_D2             56
2     Huskies_M2             55
3     Huskies_M3             54
4   Opponent1_D1              3
5   Opponent1_M1              7
6   Opponent1_D1             11
7     Huskies_F1             89
8     Huskies_F2             91

In [49]:
pd.merge(df1,df2,how='inner',on='OriginPlayerID')

OriginPlayerID  EventOrigin_x  EventOrigin_y
0   Opponent1_D1             34              3
1   Opponent1_D1             34             11
2   Opponent1_D1             41              3
3   Opponent1_D1             41             11
4     Huskies_F1             66             89
5     Huskies_F1             59             89
6     Huskies_F1             55             89
7   Opponent1_M1             36              7

pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, lef_ index=False, right_index=False, sort=True, suffixes=('x','y'), copy=True, indicator=False) left:对象 right:另一个对象 on:要加入的列（名称）。必须在左、右综合对象中找到。如果不能通过 left index和 right index是假，将推断 Dataframes中的列的交又点为连接健 left_on:从左边的综合使用作为键列。可以是列名或数组的长度等于长度综合 right on:从正确的综合，以用作键列。可以是列名或数组的长度等于长度综合 left index:如果为Tue,则使用素引（行标签）从左综合作为其联接键。在与多重（层次）的综合，级别別数必须匹配联接键从右综合的数目 right index:相同用法作为正确综合 left index how:之ー・左，右，外在、内部。默认为内部。每个方法的更详细说明请参阅： sort:综合通过联接键按字典顺序对结果进行排序。默认值为True,设置为 False将提高性能极大地在许多情况下 suffixes:字符串后缀井不适用于重列的元组。默认值为(x,'y). copy:即使重新索引是不必要总是从传递的综合对象，复制的数据(默认值True)。在许多情况下不能兔，但可能会提高性能/内存使用情况。可以避免复制 上述案件有些病理但尽管如此提供此选项。 indicator:将列添加到输出综合呼吁 merge与信息源的每一行。_ merge是绝对类型，并对观测其合并键只出现在左的综合，观测其合并键只会出现在'正确 的综合，和两个如果观察合并关健发现在两个ight_ only left_ony的值。

In [76]:
df3=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\GDP\GDP - 删减版.xlsx')
df3

Area         Value
0                           Afghanistan  1.389686e+06
1                               Albania  1.678309e+06
2                               Algeria  2.042830e+07
3                               Andorra  2.817516e+03
4                                Angola  3.101042e+07
..                                  ...           ...
205  Venezuela (Bolivarian Republic of)  1.030691e+13
206                            Viet Nam  6.037348e+09
207                               Yemen  6.240082e+06
208                              Zambia  2.975530e+05
209                            Zimbabwe  2.144076e+04

[210 rows x 2 columns]

In [77]:
df4=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿.xlsx')
df4

Area  Mineral
0                      China   618445
1              United States   392204
2                     Russia   341947
3               Saudi Arabia   231820
4                  Australia   173801
..                       ...      ...
157  Central AfricanRepublic        2
158                   Latvia        2
159                  Moldova        2
160                    Benin        1
161                 Paraguay        1

[162 rows x 2 columns]

In [78]:
df5=pd.merge(df3,df4,how='inner',on='Area')
df5

Area         Value  Mineral
0    Afghanistan  1.389686e+06      159
1        Albania  1.678309e+06     2188
2        Algeria  2.042830e+07    33810
3         Angola  3.101042e+07    34129
4      Argentina  2.165035e+07    19513
..           ...           ...      ...
116      Uruguay  1.975921e+06       54
117   Uzbekistan  5.118381e+08    11516
118        Yemen  6.240082e+06     1251
119       Zambia  2.975530e+05     4131
120     Zimbabwe  2.144076e+04     2911

[121 rows x 3 columns]

In [58]:
df5.to_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿+GDP.xlsx')

In [79]:
df6=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿量(单位t)\矿量(单位t).xlsx')
df6[:2]

Area  Total(incl.Bauxite)
0          China           4358945768
1  United States           2118592432

In [80]:
df7=pd.merge(df5,df6,how='inner',on='Area')
df7

Area         Value  Mineral  Total(incl.Bauxite)
0    Afghanistan  1.389686e+06      159              1631283
1        Albania  1.678309e+06     2188              1907690
2        Algeria  2.042830e+07    33810            138380380
3         Angola  3.101042e+07    34129             89569047
4      Argentina  2.165035e+07    19513             63402069
..           ...           ...      ...                  ...
112      Uruguay  1.975921e+06       54                16558
113   Uzbekistan  5.118381e+08    11516             54568766
114        Yemen  6.240082e+06     1251              4996200
115       Zambia  2.975530e+05     4131              1122937
116     Zimbabwe  2.144076e+04     2911              4452034

[117 rows x 4 columns]

In [69]:
df7.to_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿+GDP+矿量(单位t).xlsx')

In [81]:
df8=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\HDI\HDI-English.xlsx')
df8[:2]

Area  HDI(2019)
0   Norway      0.957
1  Ireland      0.955

In [82]:
df9=pd.merge(df7,df8,how='inner',on='Area')
df9

Area         Value  Mineral  Total(incl.Bauxite)  HDI(2019)
0    Afghanistan  1.389686e+06      159              1631283      0.511
1        Albania  1.678309e+06     2188              1907690      0.795
2        Algeria  2.042830e+07    33810            138380380      0.748
3         Angola  3.101042e+07    34129             89569047      0.581
4      Argentina  2.165035e+07    19513             63402069      0.845
..           ...           ...      ...                  ...        ...
111      Uruguay  1.975921e+06       54                16558      0.817
112   Uzbekistan  5.118381e+08    11516             54568766      0.720
113        Yemen  6.240082e+06     1251              4996200      0.470
114       Zambia  2.975530e+05     4131              1122937      0.584
115     Zimbabwe  2.144076e+04     2911              4452034      0.571

[116 rows x 5 columns]

In [83]:
df9.to_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿+GDP+矿量(单位t)+HDI(2019).xlsx')

In [84]:
df10=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\Per Capita GDP\Per Capita GDP(2020).xlsx')
df10[:2]

Area  Per Capita GDP-2020
0  Afghanistan           508.453722
1      Albania          5180.914198

In [90]:
df11=pd.merge(df9,df10,how='inner',on='Area')
df11

Area         Value  Mineral  Total(incl.Bauxite)  HDI(2019)  \
0    Afghanistan  1.389686e+06      159              1631283      0.511   
1        Albania  1.678309e+06     2188              1907690      0.795   
2        Algeria  2.042830e+07    33810            138380380      0.748   
3         Angola  3.101042e+07    34129             89569047      0.581   
4      Argentina  2.165035e+07    19513             63402069      0.845   
..           ...           ...      ...                  ...        ...   
111      Uruguay  1.975921e+06       54                16558      0.817   
112   Uzbekistan  5.118381e+08    11516             54568766      0.720   
113        Yemen  6.240082e+06     1251              4996200      0.470   
114       Zambia  2.975530e+05     4131              1122937      0.584   
115     Zimbabwe  2.144076e+04     2911              4452034      0.571   

     Per Capita GDP-2020  
0             508.453722  
1            5180.914198  
2            3367.963003  
3            1895.770703  
4            8475.729582  
..                   ...  
111         15438.401395  
112          1724.187748  
113           937.382745  
114           985.132788  
115          1465.845054  

[116 rows x 6 columns]

In [86]:
df11.to_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿+GDP+矿量(单位t)+HDI(2019)+Per Capita GDP(2020).xlsx')

In [88]:
df12=pd.read_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\World Happiness\幸福指数.xlsx')
df12[:2]

Area  Happiness
0  Finland      7.842
1  Denmark      7.620

In [93]:
df13=pd.merge(df11,df12,how='inner',on='Area')
df13

Area         Value  Mineral  Total(incl.Bauxite)  HDI(2019)  \
0    Afghanistan  1.389686e+06      159              1631283      0.511   
1        Albania  1.678309e+06     2188              1907690      0.795   
2        Algeria  2.042830e+07    33810            138380380      0.748   
3      Argentina  2.165035e+07    19513             63402069      0.845   
4        Armenia  6.569031e+06      514               322276      0.776   
..           ...           ...      ...                  ...        ...   
98       Uruguay  1.975921e+06       54                16558      0.817   
99    Uzbekistan  5.118381e+08    11516             54568766      0.720   
100        Yemen  6.240082e+06     1251              4996200      0.470   
101       Zambia  2.975530e+05     4131              1122937      0.584   
102     Zimbabwe  2.144076e+04     2911              4452034      0.571   

     Per Capita GDP-2020  Happiness  
0             508.453722      2.523  
1            5180.914198      5.117  
2            3367.963003      4.887  
3            8475.729582      5.929  
4            4266.005479      5.283  
..                   ...        ...  
98          15438.401395      6.431  
99           1724.187748      6.179  
100           937.382745      3.658  
101           985.132788      4.073  
102          1465.845054      3.145  

[103 rows x 7 columns]

In [94]:
df13.to_excel(r'E:\Study\HIT\Competition\2022-美赛  MCM&ICM\2022\F\World Data\矿+GDP+矿量(单位t)+HDI(2019)+Per Capita GDP(2020)+Happiness.xlsx')

In [96]:
df14=pd.merge(df3,df4,df5,how='inner',on='Area')
df13

TypeError: merge() got multiple values for argument 'how'

In [61]:
(np.array([0.1711218, 0.25894589, 0.16571772, 0.1637781, 0.10797606, 0.12058573,  0.0118747])+np.array([0.17113626, 0.25863544, 0.1657511, 0.16381455, 0.10808147, 0.12068926, 0.01189193])+np.array([0.17111012, 0.25923732, 0.16568888, 0.16374394, 0.10787516, 0.1204887, 0.01185589]))/3

array([0.17112273, 0.25893955, 0.16571923, 0.16377886, 0.10797756,
       0.1205879 , 0.01187417])

In [64]:
(np.array([0.14754709, 0.18772292, 0.1595641, 0.14088955, 0.13239418, 0.11925406, 0.11262811])
+np.array([0.14759167, 0.18719075, 0.15957803, 0.14096597, 0.13253801, 0.11937829, 0.11275727])
+np.array([0.14753803, 0.18797674, 0.15954368, 0.14084362, 0.13233761, 0.11919018, 0.11257014]))/3

array([0.14755893, 0.18763014, 0.15956194, 0.14089971, 0.13242327,
       0.11927418, 0.11265184])

In [ ]:
array([0.14755893, 0.18763014, 0.15956194, 0.14089971, 0.13242327,
       0.11927418, 0.11265184])