In [20]:
import numpy as np
import sympy as sp
import xlrd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
A=[[1,2,2,3],[1,4,-3,6],[-2,-6,1,-9],[1,4,-1,7],[4,8,2,9]]#A为数组
A

[[1, 2, 2, 3], [1, 4, -3, 6], [-2, -6, 1, -9], [1, 4, -1, 7], [4, 8, 2, 9]]

In [6]:
A=np.array(A)
A

array([[ 1,  2,  2,  3],
       [ 1,  4, -3,  6],
       [-2, -6,  1, -9],
       [ 1,  4, -1,  7],
       [ 4,  8,  2,  9]])

In [14]:
B=sp.Matrix(A)
B

Matrix([
[ 1,  2,  2,  3],
[ 1,  4, -3,  6],
[-2, -6,  1, -9],
[ 1,  4, -1,  7],
[ 4,  8,  2,  9]])

In [17]:
A=A.T
A

array([[ 1,  1, -2,  1,  4],
       [ 2,  4, -6,  4,  8],
       [ 2, -3,  1, -1,  2],
       [ 3,  6, -9,  7,  9]])

In [18]:
B=B.T
B

Matrix([
[1,  1, -2,  1, 4],
[2,  4, -6,  4, 8],
[2, -3,  1, -1, 2],
[3,  6, -9,  7, 9]])

In [19]:
B.rref()

(Matrix([
 [1, 0, -1, 0,  4],
 [0, 1, -1, 0,  3],
 [0, 0,  0, 1, -3],
 [0, 0,  0, 0,  0]]),
 (0, 1, 3))

A为方阵时，可用np.linalg.eigvals(A)求特征值，  不为时用奇异值分解

In [22]:
np.sum(B,axis=0)

array([8, 8, -16, 11, 23], dtype=object)